### ISSUE TITLE
Storing of keyfile on Linux fails due to java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by purejava** [jht5945/gnupg-cryptomator#1]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-cryptomator/issues?q=) for duplicates

### Summary

Cannot save password for vault

### What software is involved?

- Operating System: Arch Linux 
- Cryptomator 1.12.3 on Linux 6.9.3-1-aarch64-ARCH (aarch64), cryptomator.buildNumber: aur-2

### Steps to Reproduce

1. Enable this plugin in the Cryptomator settings
2. Unlock a vault and tick the checkbox to store the password in the pop-up

### Expected Behavior

Password gets stored in an encrypted file on the filesystem.

### Actual Behavior

Storing the file fails.

### Reproducibility

Only once.

### Relevant Log Output

```shell
13:38:49.100 [App Background Thread 004] ERROR o.c.ui.keyloading.KeyLoadingStrategy - Failed to store passphrase in system keychain.
org.cryptomator.integrations.keychain.KeychainAccessException: Run GnuPG command failed: [gpg, -r, 54CF8E1F55CE7E977A0E41895BFB2076ABC48776, -e, -a, --no-comment, --comment, Cryptomator: test]
	at me.hatter.integrations.keychain.Utils.runGpgPG(Utils.java:203)
	at me.hatter.integrations.keychain.Utils.encrypt(Utils.java:137)
	at me.hatter.integrations.keychain.Utils.storePassword(Utils.java:77)
	at me.hatter.integrations.keychain.GnuPGAccessProvider.storePassphrase(GnuPGAccessProvider.java:53)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.common.keychain.KeychainManager.storePassphrase(KeychainManager.java:48)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.ui.keyloading.masterkeyfile.MasterkeyFileLoadingStrategy.savePasswordToSystemkeychain(MasterkeyFileLoadingStrategy.java:117)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.ui.keyloading.masterkeyfile.MasterkeyFileLoadingStrategy.cleanup(MasterkeyFileLoadingStrategy.java:107)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:89)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:76)
	at org.cryptomator.desktop@1.12.3/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:34)
	at javafx.graphics@21.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(Unknown Source)
	at java.base/java.io.OutputStream.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.implFlush(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
	at java.base/java.io.FilterOutputStream.close(Unknown Source)
	at me.hatter.integrations.keychain.Utils.lambda$runGpgPG$0(Utils.java:166)
	... 1 common frames omitted
```

### Anything else?

I could not reproduce the issue and had it only once on my first test of the plugin.
I suspect that something was wrong with my gpg-agent.

**Comment by jht5945** [comment]
Accounting the error message, maybe I can do nothing, it looks like `gpg` process is unexpected down. My computers all MacBook, I will try on Linux in a virtual machine when I have a chance.
